// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcxsjrYT2xRw1sMWCrkl1xaMOlKWHaxeQ',
    appId: '1:384411993244:web:6800c1bc0f496e6eb21959',
    messagingSenderId: '384411993244',
    projectId: 'inshort-a8062',
    authDomain: 'inshort-a8062.firebaseapp.com',
    storageBucket: 'inshort-a8062.appspot.com',
    measurementId: 'G-QR4PHCSFPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrwo951JfE8wDns8jYUEZ9rs59nxgglmo',
    appId: '1:384411993244:android:31b4dbc9db19e0bcb21959',
    messagingSenderId: '384411993244',
    projectId: 'inshort-a8062',
    storageBucket: 'inshort-a8062.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAUd4C9a38r_NtDo_dV3heLb0GhrTlrwI',
    appId: '1:384411993244:ios:457b5a209bf967afb21959',
    messagingSenderId: '384411993244',
    projectId: 'inshort-a8062',
    storageBucket: 'inshort-a8062.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAUd4C9a38r_NtDo_dV3heLb0GhrTlrwI',
    appId: '1:384411993244:ios:457b5a209bf967afb21959',
    messagingSenderId: '384411993244',
    projectId: 'inshort-a8062',
    storageBucket: 'inshort-a8062.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcxsjrYT2xRw1sMWCrkl1xaMOlKWHaxeQ',
    appId: '1:384411993244:web:ea7f6715ea0d9f9bb21959',
    messagingSenderId: '384411993244',
    projectId: 'inshort-a8062',
    authDomain: 'inshort-a8062.firebaseapp.com',
    storageBucket: 'inshort-a8062.appspot.com',
    measurementId: 'G-NXQ3L78NTJ',
  );
}
